#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar
#
# # Wait until the processes have been shut down
  polybar --reload top -c ~/.config/polybar/config &
## Launch bar1 and bar2
#
#
